/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usser
 */
public class AddFrame extends javax.swing.JFrame {

    int rowCount = 0;

    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
        txtVisibleFalseWithoutId(true);
        jButton2.setEnabled(false);
        ProductTable.setEnabled(false);
        jButton1.setEnabled(false);
        ProductTable.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Barkod No veya ID");
        defaultTableModel.addColumn("İsim");
        defaultTableModel.addColumn("Marka");
        defaultTableModel.addColumn("Alış Fiyatı");
        defaultTableModel.addColumn("Satış Fiyatı");
        defaultTableModel.addColumn("Stok");
        defaultTableModel.addColumn("Uyarı Limiti");
        defaultTableModel.addColumn("Alış Tarihi"); //alış tarihi
        ProductTable.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_SellPrice = new javax.swing.JTextField();
        txt_ID1 = new javax.swing.JTextField();
        txt_Name1 = new javax.swing.JTextField();
        txt_Stock1 = new javax.swing.JTextField();
        txt_Brand1 = new javax.swing.JTextField();
        txt_BuyPrice1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        lbl_IDControll = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_warnLimit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_IdControl = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ürün Ekleme");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sellprice.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 46));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 51, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product_name.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 46));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/price.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, 46));
        getContentPane().add(txt_SellPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 120, -1));

        txt_ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));
        getContentPane().add(txt_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));
        getContentPane().add(txt_Stock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, -1));
        getContentPane().add(txt_Brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 120, -1));
        getContentPane().add(txt_BuyPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, -1));

        jLabel7.setText("Satış Fiyatı:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, -1));

        jLabel8.setText("Ürün Adı:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, -1));

        jLabel9.setText("Adet:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, -1));

        jLabel10.setText("Marka:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 70, -1));

        jLabel11.setText("Alış Fiyatı:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 90, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ok-icon.png"))); // NOI18N
        jButton1.setText("Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 90, 40));

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ProductTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 910, 230));
        getContentPane().add(lbl_IDControll, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, 20));

        jLabel12.setText("Barkod or ID:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Eklenen Ürünler");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 120, -1));
        getContentPane().add(txt_warnLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 120, -1));

        jLabel14.setText("Limit Uyarısı:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 100, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warn3.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 46));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brand.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 46));

        btn_IdControl.setText("Kontrol Et");
        btn_IdControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IdControlActionPerformed(evt);
            }
        });
        getContentPane().add(btn_IdControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jButton2.setText("Tekrar Kontrol Et");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jButton3.setText("Geri");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Date nowDate = new Date();
            DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
            
            String a = "";

            if (!Methods.regexStringControl(txt_Name1.getText())) {
                a += "Name, ";
            }
            if (!Methods.regexStringControl(txt_Brand1.getText())) {
                a += "Brand, ";
            }
            if (!txt_Stock1.getText().matches("\\d+")) {
                a += "Stock, ";

            }
            if (!Methods.regexControl(txt_BuyPrice1.getText()) || txt_BuyPrice1.getText().contains(" ")) {
                a += "Purchase Price, ";

            }
            if (!Methods.regexControl(txt_SellPrice.getText()) || txt_SellPrice.getText().contains(" ")) {
                a += "Sale Price, ";

            }
            if (!txt_warnLimit.getText().matches("\\d+")) {
                a += "Warning Limit, ";

            }
            if ((!txt_Stock1.getText().matches("\\d+")) || (!Methods.regexControl(txt_BuyPrice1.getText())) || (!Methods.regexControl(txt_SellPrice.getText())) || (!txt_warnLimit.getText().matches("\\d+")) || (txt_SellPrice.getText().contains(" ")) || txt_BuyPrice1.getText().contains(" ") || (!Methods.regexStringControl(txt_Name1.getText())) || (!Methods.regexStringControl(txt_Brand1.getText()))) {
                JOptionPane.showMessageDialog(null, a + "Hatalı Giriş!", "HATA", 0);
            } else {
                Connector.connect();
                Product product = new Product(Integer.parseInt(txt_ID1.getText()), txt_Name1.getText(), txt_Brand1.getText(), Double.parseDouble(txt_BuyPrice1.getText().replaceAll(",", ".")), Double.parseDouble(txt_SellPrice.getText().replaceAll(",", ".")), Double.parseDouble(txt_Stock1.getText()), Integer.parseInt(txt_warnLimit.getText()));
                String query = "insert into products(ID,Name,Brand,BuyPrice,SellPrice,Stock,WarnLimit,AlısTarihi) values(?,?,?,?,?,?,?,now())";
                PreparedStatement ps = Connector.conn.prepareStatement(query);
                ps.setInt(1, product.getID());
                ps.setString(2, product.getName());
                ps.setString(3, product.getBrand());
                ps.setDouble(4, product.getBuyPrice());
                ps.setDouble(5, product.getSellPrice());
                ps.setDouble(6, product.getStock());
                ps.setInt(7, product.getWarnLimit());
                ps.execute();

                DefaultTableModel productmodel = (DefaultTableModel) ProductTable.getModel();
                productmodel.setRowCount(rowCount++);
                productmodel.addRow(new Object[]{
                    product.getID(), product.getName(), product.getBrand(),
                    product.getBuyPrice(), product.getSellPrice(), new DecimalFormat("##").format(product.getStock()), product.getWarnLimit(), df.format(nowDate)
                });

                productmodel.fireTableDataChanged();
                JOptionPane.showMessageDialog(null, "EKLENDİ");
                txtResetMethod();
                lbl_IDControll.setText("");
                txt_ID1.setEnabled(true);
                btn_IdControl.setEnabled(true);
                txtVisibleFalseWithoutId(true);
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        Connector.disconnect();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void txtVisibleFalseWithoutId(boolean temp) {
        txt_Name1.setEnabled(!temp);
        txt_Stock1.setEnabled(!temp);
        txt_Brand1.setEnabled(!temp);
        txt_warnLimit.setEnabled(!temp);
        txt_BuyPrice1.setEnabled(!temp);
        txt_SellPrice.setEnabled(!temp);
    }

    public void txtResetMethod() {
        txt_ID1.setText("");
        txt_Name1.setText("");
        txt_Brand1.setText("");
        txt_BuyPrice1.setText("");
        txt_Stock1.setText("");
        txt_SellPrice.setText("");
        txt_warnLimit.setText("");
    }

    private void txt_ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID1ActionPerformed

    }//GEN-LAST:event_txt_ID1ActionPerformed

    private void btn_IdControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IdControlActionPerformed
        PreparedStatement p1;
        try {
            if (txt_ID1.getText().matches("\\d+")) {
                Connector.connect();
                p1 = Connector.conn.prepareStatement("select * from products");
                ResultSet resultSet = p1.executeQuery();
                boolean controlBool = false;
                while (resultSet.next()) {
                    if (resultSet.getInt("ID") == Integer.parseInt(txt_ID1.getText())) {
                        lbl_IDControll.setText(txt_ID1.getText() + " " + "KULLANILMIŞ");
                        txt_ID1.setText("");
                        controlBool = true;
                        break;
                    } else {
                        controlBool = false;
                    }
                }
                if (!controlBool) {
                    lbl_IDControll.setText(txt_ID1.getText() + " " + "KULLANILMAMIŞ");
                    txtVisibleFalseWithoutId(false);
                    txt_ID1.setEnabled(false);
                    btn_IdControl.setEnabled(false);
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                    txt_ID1.setEnabled(false);
                    btn_IdControl.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Hatalı ID Girişi, Lütfen Sayı Giriniz", "HATA", 0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        Connector.disconnect();
    }//GEN-LAST:event_btn_IdControlActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txt_ID1.setEnabled(true);
        btn_IdControl.setEnabled(true);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        txtVisibleFalseWithoutId(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        MainView main = new MainView();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainView main = new MainView();
        main.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton btn_IdControl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_IDControll;
    private javax.swing.JTextField txt_Brand1;
    private javax.swing.JTextField txt_BuyPrice1;
    private javax.swing.JTextField txt_ID1;
    private javax.swing.JTextField txt_Name1;
    private javax.swing.JTextField txt_SellPrice;
    private javax.swing.JTextField txt_Stock1;
    private javax.swing.JTextField txt_warnLimit;
    // End of variables declaration//GEN-END:variables
}
