/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usser
 */
public class ReportFrame extends javax.swing.JFrame {

    ArrayList list = new ArrayList();

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
        initComponents();
        ProductTable.setVisible(false);
        ProductTable.setEnabled(false);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_StockReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Raporlar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_StockReport.setText("Stok Raporu");
        btn_StockReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StockReportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_StockReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stockrapor.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ProductTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 900, 240));

        jButton1.setText("Limit uyarısı");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 170, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jButton3.setText("Geri");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jButton2.setText("İsme göre sırala");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, 40));

        jButton4.setText("Markaya göre sırala");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StockReportActionPerformed
        list.removeAll(list);
        ProductTable.setVisible(true);
        int rowCount = 0;
        try {
            ProductTable.setModel(new DefaultTableModel(
                    new Object[][]{},
                    new String[]{}
            ));
            DefaultTableModel defaultTableModel = new DefaultTableModel();
            defaultTableModel.addColumn("Barkod No veya ID");
            defaultTableModel.addColumn("İsim");
            defaultTableModel.addColumn("Marka");
            defaultTableModel.addColumn("Alış Fiyatı");
            defaultTableModel.addColumn("Satış Fiyatı");
            defaultTableModel.addColumn("Stok");
            defaultTableModel.addColumn("Alış Tarihi");
            ProductTable.setModel(defaultTableModel);
            Connector.connect();
            PreparedStatement ps = Connector.conn.prepareStatement("select * from products");
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {
                Product product = new Product(resultSet.getInt("ID"), resultSet.getString("Name"), resultSet.getString("Brand"), resultSet.getDouble("BuyPrice"), resultSet.getDouble("SellPrice"),
                        resultSet.getDouble("Stock"), resultSet.getInt("WarnLimit"));
                list.add(product);
                DefaultTableModel productmodel = (DefaultTableModel) ProductTable.getModel();
                productmodel.setRowCount(rowCount++);
                productmodel.addRow(new Object[]{
                    product.getID(), product.getName(), product.getBrand(),
                    product.getBuyPrice(), product.getSellPrice(), new DecimalFormat("##").format(product.getStock()), resultSet.getDate("AlısTarihi")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connector.disconnect();
        jButton2.setEnabled(true);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_btn_StockReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProductTable.setVisible(true);
        int rowCount = 0;
        try {
            ProductTable.setModel(new DefaultTableModel(
                    new Object[][]{},
                    new String[]{}
            ));
            DefaultTableModel defaultTableModel = new DefaultTableModel();
            defaultTableModel.addColumn("Barkod No veya ID");
            defaultTableModel.addColumn("İsim");
            defaultTableModel.addColumn("Marka");
            defaultTableModel.addColumn("Alış Fiyatı");
            defaultTableModel.addColumn("Satış Fiyatı");
            defaultTableModel.addColumn("Stok");
            defaultTableModel.addColumn("Uyarı Limiti");
            defaultTableModel.addColumn("Alış Tarihi");
            ProductTable.setModel(defaultTableModel);
            Connector.connect();
            PreparedStatement ps = Connector.conn.prepareStatement("select * from products");
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {
                if (resultSet.getInt("Stock") < resultSet.getInt("WarnLimit")) {
                    Product product = new Product(resultSet.getInt("ID"), resultSet.getString("Name"), resultSet.getString("Brand"), resultSet.getDouble("BuyPrice"), resultSet.getDouble("SellPrice"),
                            resultSet.getDouble("Stock"), resultSet.getInt("WarnLimit"));
                    DefaultTableModel productmodel = (DefaultTableModel) ProductTable.getModel();
                    productmodel.setRowCount(rowCount++);
                    productmodel.addRow(new Object[]{
                        product.getID(), product.getName(), product.getBrand(),
                        product.getBuyPrice(), product.getSellPrice(), new DecimalFormat("##").format(product.getStock()), product.getWarnLimit(), resultSet.getDate("AlısTarihi")
                    });
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connector.disconnect();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainView main = new MainView();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rowCount = 0;

        Collections.sort(list);
        ProductTable.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Barkod No veya ID");
        defaultTableModel.addColumn("İsim");
        defaultTableModel.addColumn("Marka");
        defaultTableModel.addColumn("Alış Fiyatı");
        defaultTableModel.addColumn("Satış Fiyatı");
        defaultTableModel.addColumn("Stok");
        defaultTableModel.addColumn("Uyarı Limiti");
        ProductTable.setModel(defaultTableModel);
        for (int i = 0; i < list.size(); i++) {
            Product product = (Product) list.get(i);
            DefaultTableModel productmodel = (DefaultTableModel) ProductTable.getModel();
            productmodel.setRowCount(rowCount++);
            productmodel.addRow(new Object[]{
                product.getID(), product.getName(), product.getBrand(),
                product.getBuyPrice(), product.getSellPrice(), new DecimalFormat("##").format(product.getStock()), product.getWarnLimit()
            });
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int rowCount = 0;

        Collections.sort(list,new ProductComparator());
        ProductTable.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Barkod No veya ID");
        defaultTableModel.addColumn("İsim");
        defaultTableModel.addColumn("Marka");
        defaultTableModel.addColumn("Alış Fiyatı");
        defaultTableModel.addColumn("Satış Fiyatı");
        defaultTableModel.addColumn("Stok");
        defaultTableModel.addColumn("Uyarı Limiti");
        ProductTable.setModel(defaultTableModel);
        for (int i = 0; i < list.size(); i++) {
            Product product = (Product) list.get(i);
            DefaultTableModel productmodel = (DefaultTableModel) ProductTable.getModel();
            productmodel.setRowCount(rowCount++);
            productmodel.addRow(new Object[]{
                product.getID(), product.getName(), product.getBrand(),
                product.getBuyPrice(), product.getSellPrice(), new DecimalFormat("##").format(product.getStock()), product.getWarnLimit()
            });
        }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new MainView().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton btn_StockReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
